services:
  connector:
    image: ${CONNECTOR_IMAGE:-ghcr.io/dataspace-rs/connector:0.11.1}
    ports:
      - "19191:9191" # connector default
      - "19192:9192" # connector control
      - "19193:9193" # connector management
      - "19194:9194" # connector protocol
      - "19291:9291" # data-plane public
    environment:
      EDC_VAULT: /config/vault.properties
      EDC_KEYSTORE: /config/vault-keys.p12
      EDC_KEYSTORE_PASSWORD: 123456
      EDC_FS_CONFIG: /config/configuration.properties
    volumes:
      - ./conf/consumer-connector.config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"

  edc-web-ui:
    image: ${EDC_WEB_UI_IMAGE:-ghcr.io/dataspace-rs/edc-web-ui:main}
    ports:
      - "8080:80"
    volumes:
      - ./conf/nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/configuration.json:/usr/share/nginx/html/configuration.json
